name: CoreErlang
version: '0.0.5'
synopsis: "Manipulating Core Erlang source code"
description: "Facilities for manipulating Core Erlang source code: an abstract syntax, parser and pretty-printer."
category: Language
license: BSD3
author: "David Castro Pérez <dcastrop@udc.es>, Henrique Ferreiro García <hferreiro@udc.es>"
maintainer: "Alex Kropivny <alex.kropivny@gmail.com>, Feng Lee <feng@emqx.io>"
copyright: "2008, David Castro Pérez, Henrique Ferreiro García"
github: hamler-lang/CoreErlang
homepage: https://github.com/hamler-lang/CoreErlang

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- pretty >=1.1 && <1.2
- parsec >=3.1 && <3.2

library:
  source-dirs: src
  ghc-options: -Wall -O2
  default-extensions:
  - DeriveDataTypeable
  - LambdaCase

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CoreErlang
    default-extensions:
    - DeriveDataTypeable
    - LambdaCase
